name: Pull Request Checks

on:
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: swift:6.1.2
    steps:
      - name: Install Git LFS
        run: |
          apt-get update
          apt-get install -y git-lfs
          git lfs install

      - name: Checkout repo with LFS
        uses: actions/checkout@v4
        with:
          lfs: true
          path: subject

      - name: Cache swift-format binary
        id: get-swift-format-from-cache
        uses: actions/cache/restore@v4
        with:
          path: swift-format-bin
          key: swift-format-${{ runner.os }}-v1

      - name: Build swift-format (only if not cached)
        if: steps.get-swift-format-from-cache.outputs.cache-hit != 'true'
        run: /ci/build_swift_format.sh

      - name: Save swift-format to cache (only if not cached)
        if: steps.get-swift-format-from-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: swift-format-bin
          key: swift-format-${{ runner.os }}-v1

      - name: Make swift-format available
        run: |
          cp swift-format-bin/swift-format /usr/local/bin

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Check if git is normalized
        run: /ci/check_git_normal.sh

      - name: Check Code Formatting (Swift)
        run: /ci/check_swift_format.sh
